### ISSUE TITLE
The training details

### ISSUE THREAD

**Issue by range428** [tiankongzhang/MGAD#1]
I use the code in your depository to train, 36 rounds in the first stage and 25 rounds in the second stage. In cityscapes2foggy, I can't achieve better results than 41.5ap. I hope to get your advice.

The final training result of my first stage is usually between 37ap-38ap, but it will appear 39ap in more than 20 rounds. In the second stage, the model output at the 36th stage of the first stage is used to continue the training, but the best is 41.5, what can I do to improve the performance?

My configuration is two 24g NVIDIA graphics cards，model configuration is the same as that in your depository VGG>s0 and VGG>s1.

**s0**

```
Namespace(config_file=./MGADA/Faster-RCNN/configs/mgad/cityscape_to_foggy/VGG/s0/adv_vgg16_cityscapes_2_foggy.yaml', dist_backend='nccl', dist_url='env://', distributed=True, gpu=0, local_rank=0, opts=[], rank=0, resume='', test_only=False, use_current_epoch=False, world_size=2)
Change lr from 0.0003 to 0.00015
ADV:
  DIS_MODEL: [{'in_channels': 512, 'func_name': 'cross_entropy', 'pool_type': 'avg', 'loss_weight': 1.0, 'window_strides': [2, 2, 2, 2, 2, 2, 2], 'window_sizes': [3, 9, 15, 21, 27, 33, 37]}]
  FOCAL_LOSS_GAMMA: 5
  LAMBDA_FROM: 1.0
  LAMBDA_TO: 1.0
  LAYERS: [False, False, True]
  LOSS_FUNC: focal_loss
  LOSS_WEIGHT: 1.0
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TARGETS: ('foggy_cityscapes_train_0.02',)
  TESTS: ('foggy_cityscapes_val_0.02',)
  TRAINS: ('cityscapes_train',)
INPUT:
  TRANSFORMS_TEST: [{'name': 'resize', 'min_size': 600}, {'name': 'normalize', 'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5], 'to_01': True}, {'name': 'collect'}]
  TRANSFORMS_TRAIN: [{'name': 'random_flip'}, {'name': 'resize', 'min_size': 600}, {'name': 'normalize', 'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5], 'to_01': True}, {'name': 'collect'}]
MODEL:
  BACKBONE:
    NAME: vgg16
  GENFEATURE:
    FPN_STRIDES: [0.0625]
    LOCAL_GLOBAL_MERGE: True
    TWOMULTSCALE: True
  MASK_ON: False
  ROI_BOX_HEAD:
    BOX_PREDICTOR: vgg16_predictor
    NUM_CLASSES: 9
    POOL_RESOLUTION: 7
    POOL_SPATIAL_SCALE: 0.0625
    POOL_TYPE: align
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    DETECTIONS_PER_IMG: 100
    NMS_THRESH_TEST: 0.5
    SCORE_THRESH_TEST: 0.0
  ROI_ONE_DIS:
    CLS:
      DISCRIMINATOR: OneFCOSDiscriminator_cc
      GRL_LAMBDA: 0.01
      LOSS_DIRECT_W: 1.0
      LOSS_GRL_W: 0.1
      LOSS_WEIGHT: 0.1
      MON: True
      NUM_CLASSES: 2
      NUM_CONVS: 3
      SAMPLES_THRESH: 0.8
    DOM:
      DISCRIMINATOR: OneFCOSDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 0.1
      MON: True
      NUM_CONVS: 3
  ROI_TWO_DIS:
    CLS:
      DISCRIMINATOR: VGG16TwoDiscriminator_cc
      GRL_LAMBDA: 0.02
      LOSS_DIRECT_W: 0.1
      LOSS_GRL_W: 0.1
      LOSS_WEIGHT: 0.1
      MON: False
      NUM_CLASSES: 9
      POOL_RESOLUTION: 7
      SAMPLES_THRESH: 0.6
      SAMPLE_WEIGHTS: 1.0
    DOM:
      DISCRIMINATOR: VGG16TwoDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 0.1
      MON: True
      POOL_RESOLUTION: 7
      SAMPLE_WEIGHTS: 1.0
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: 16
    ASPECT_RATIOS: (0.5, 1, 2)
    BATCH_SIZE_PER_IMAGE: 256
    MIN_SIZE: 1
    NMS_THRESH: 0.7
    NUM_CHANNELS: 512
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 36
  GAMMA: 0.1
  LR: 0.00015
  MOMENTUM: 0.9
  STEPS: (1600, 2600)
  WEIGHT_DECAY: 0.0001
TEST:
  EVAL_TYPES: ('voc',)
WORK_DIR: ./debug/cityscape_to_foggy/s0/adv_cityscapes_2_foggy
loading annotations into memory...
Done (t=0.44s)
creating index...
index created!
loading annotations into memory...
Done (t=1.88s)
creating index...
index created!
loading annotations into memory...
Done (t=0.60s)
creating index...
index created!
Start training, total epochs: 36 (0 - 35), total steps: 3348
./anaconda3/envs/mgadacu11/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
./anaconda3/envs/mgadacu11/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
./anaconda3/envs/mgadacu11/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
./anaconda3/envs/mgadacu11/lib/python3.7/site-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
```

**s1**
```powershell
Namespace(config_file='./MGADA/Faster-RCNN/configs/mgad/cityscape_to_foggy/VGG/s1/adv_vgg16_cityscapes_2_foggy.yaml', dist_backend='nccl', dist_url='env://', distributed=True, gpu=0, local_rank=0, opts=[], rank=0, resume='./debug/cityscape_to_foggy/s0/adv_cityscapes_2_foggy/model_epoch_35.pth', test_only=False, use_current_epoch=False, world_size=2)
Change lr from 0.0003 to 0.00015
ADV:
  DIS_MODEL: [{'in_channels': 512, 'func_name': 'cross_entropy', 'pool_type': 'avg', 'loss_weight': 1.0, 'window_strides': [2, 2, 2, 2, 2, 2, 2], 'window_sizes': [3, 9, 15, 21, 27, 33, 37]}]
  FOCAL_LOSS_GAMMA: 5
  LAMBDA_FROM: 1.0
  LAMBDA_TO: 1.0
  LAYERS: [False, False, True]
  LOSS_FUNC: focal_loss
  LOSS_WEIGHT: 1.0
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TARGETS: ('foggy_cityscapes_train_0.02',)
  TESTS: ('foggy_cityscapes_val_0.02',)
  TRAINS: ('cityscapes_train',)
INPUT:
  TRANSFORMS_TEST: [{'name': 'resize', 'min_size': 600}, {'name': 'normalize', 'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5], 'to_01': True}, {'name': 'collect'}]
  TRANSFORMS_TRAIN: [{'name': 'random_flip'}, {'name': 'resize', 'min_size': 600}, {'name': 'normalize', 'mean': [0.5, 0.5, 0.5], 'std': [0.5, 0.5, 0.5], 'to_01': True}, {'name': 'collect'}]
MODEL:
  BACKBONE:
    NAME: vgg16
  GENFEATURE:
    FPN_STRIDES: [0.0625]
    LOCAL_GLOBAL_MERGE: True
    TWOMULTSCALE: True
  MASK_ON: False
  ROI_BOX_HEAD:
    BOX_PREDICTOR: vgg16_predictor
    NUM_CLASSES: 9
    POOL_RESOLUTION: 7
    POOL_SPATIAL_SCALE: 0.0625
    POOL_TYPE: align
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    DETECTIONS_PER_IMG: 100
    NMS_THRESH_TEST: 0.5
    SCORE_THRESH_TEST: 0.0
  ROI_ONE_DIS:
    CLS:
      DISCRIMINATOR: OneFCOSDiscriminator_cc
      GRL_LAMBDA: 0.01
      LOSS_DIRECT_W: 1.0
      LOSS_GRL_W: 1.0
      LOSS_WEIGHT: 1.0
      MON: False
      NUM_CLASSES: 1
      NUM_CONVS: 4
      SAMPLES_THRESH: 0.5
    DOM:
      DISCRIMINATOR: OneFCOSDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 0.1
      MON: True
      NUM_CONVS: 3
  ROI_TWO_DIS:
    CLS:
      DISCRIMINATOR: VGG16TwoDiscriminator_cc
      GRL_LAMBDA: 0.02
      LOSS_DIRECT_W: 0.1
      LOSS_GRL_W: 0.1
      LOSS_WEIGHT: 0.1
      MON: False
      NUM_CLASSES: 9
      POOL_RESOLUTION: 7
      SAMPLES_THRESH: 0.6
      SAMPLE_WEIGHTS: 1.0
    DOM:
      DISCRIMINATOR: VGG16TwoDiscriminator
      GRL_LAMBDA: 0.01
      LOSS_WEIGHT: 0.1
      MON: True
      POOL_RESOLUTION: 7
      SAMPLE_WEIGHTS: 1.0
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: 16
    ASPECT_RATIOS: (0.5, 1, 2)
    BATCH_SIZE_PER_IMAGE: 256
    MIN_SIZE: 1
    NMS_THRESH: 0.7
    NUM_CHANNELS: 512
    POST_NMS_TOP_N_TEST: 300
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
SOLVER:
  BATCH_SIZE: 16
  EPOCHS: 25
  GAMMA: 0.1
  LR: 0.00015
  MOMENTUM: 0.9
  STEPS: (8, 16, 22)
  WEIGHT_DECAY: 0.0001
TEST:
  EVAL_TYPES: ('voc',)`
```
